@startuml
class LogItem{
    - int programId
    - String thoiGian
    - String noiDung
}

class Logger{
    - static Logger instance
    - Logger()
    + static Logger getInstance()
    + String log(int programId, String noiDung)
}

class Program{
    - int programId
    + String log(String noiDung)
}

Program --> Logger: logger
Logger o--> "*" LogItem: items

@enduml