@startuml
class Notification{
    - String tieuDe
    - String noiDung
    - String bieuTuong
    - String amThanh
    - String nutHanhDong
    - int doUuTien
    - Notification(Builder builder)
}

class Builder{
    - String tieuDe
    - String noiDung
    - String bieuTuong
    - String amThanh
    - String nutHanhDong
    - int doUuTien
    + Builder()
    + Builder withTieuDe(String tieuDe)
    + Builder withNoiDung(String noiDung)
    + Builder withBieuTuong(String bieuTuong)
    + Builder withAmThanh(String amThanh)
    + Builder withNutHanhDong(String nutHanhDong)
    + Builder withDoUuTien(int doUuTien)
    + Notification build()
}

Builder ..> Notification
@enduml